"use client";

import { useState, useEffect } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import {
  ArrowLeft,
  Download,
  FileCode,
  Loader2,
  Network,
  Table,
  Box,
  FileJson,
  FileText,
} from "lucide-react";
import { outputsApi, OutputFile } from "@/lib/api/outputs";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

const FILE_TYPE_CONFIG: Record<string, { icon: React.ComponentType<any>; label: string; color: string }> = {
  knowledge_graph: { icon: Network, label: "Knowledge Graph", color: "text-purple-500" },
  embeddings: { icon: Box, label: "Embeddings", color: "text-blue-500" },
  tabular_csv: { icon: Table, label: "Tabular Data (CSV)", color: "text-green-500" },
  tabular_parquet: { icon: Table, label: "Tabular Data (Parquet)", color: "text-green-500" },
  gnn_structure: { icon: Network, label: "GNN Structure", color: "text-orange-500" },
  summary: { icon: FileJson, label: "Summary", color: "text-cyan-500" },
  report: { icon: FileText, label: "Report", color: "text-gray-500" },
  ids_rules: { icon: FileCode, label: "IDS Rules", color: "text-yellow-500" },
  other: { icon: FileCode, label: "Other", color: "text-muted-foreground" },
};

export default function OutputsPage() {
  const params = useParams();
  const projectId = params.id as string;

  const [files, setFiles] = useState<OutputFile[]>([]);
  const [totalSize, setTotalSize] = useState(0);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchOutputs = async () => {
      try {
        const data = await outputsApi.list(projectId);
        setFiles(data.files || data || []);
        setTotalSize(data.total_size_kb || 0);
      } catch (e) {
        console.error("Failed to load outputs:", e);
      } finally {
        setIsLoading(false);
      }
    };

    fetchOutputs();
  }, [projectId]);

  const handleDownloadAll = () => {
    window.open(outputsApi.downloadAllUrl(projectId), "_blank");
  };

  if (isLoading) {
    return (
      <div className="flex h-[50vh] items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  // Group files by type
  const groupedFiles = files.reduce((acc, file) => {
    const type = file.file_type;
    if (!acc[type]) acc[type] = [];
    acc[type].push(file);
    return acc;
  }, {} as Record<string, OutputFile[]>);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div className="space-y-1">
          <Link
            href={`/projects/${projectId}`}
            className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to Project
          </Link>
          <h1 className="text-3xl font-bold tracking-tight">Pipeline Outputs</h1>
          <p className="text-muted-foreground">
            Download AI-ready data formats generated by the pipeline
          </p>
        </div>
        <Button onClick={handleDownloadAll} disabled={files.length === 0}>
          <Download className="mr-2 h-4 w-4" />
          Download All ({formatSize(totalSize)})
        </Button>
      </div>

      {/* Quick Links */}
      <div className="grid gap-4 md:grid-cols-4">
        <Link href={`/projects/${projectId}/outputs/knowledge-graph`}>
          <Card className="h-full transition-colors hover:bg-muted/50">
            <CardContent className="flex items-center gap-4 pt-6">
              <Network className="h-10 w-10 text-purple-500" />
              <div>
                <h3 className="font-medium">Knowledge Graph</h3>
                <p className="text-sm text-muted-foreground">Interactive visualization</p>
              </div>
            </CardContent>
          </Card>
        </Link>
        <Link href={`/projects/${projectId}/outputs/embeddings`}>
          <Card className="h-full transition-colors hover:bg-muted/50">
            <CardContent className="flex items-center gap-4 pt-6">
              <Box className="h-10 w-10 text-blue-500" />
              <div>
                <h3 className="font-medium">Embeddings</h3>
                <p className="text-sm text-muted-foreground">Vector visualization</p>
              </div>
            </CardContent>
          </Card>
        </Link>
        <Link href={`/projects/${projectId}/outputs/tabular`}>
          <Card className="h-full transition-colors hover:bg-muted/50">
            <CardContent className="flex items-center gap-4 pt-6">
              <Table className="h-10 w-10 text-green-500" />
              <div>
                <h3 className="font-medium">Tabular Data</h3>
                <p className="text-sm text-muted-foreground">Data preview</p>
              </div>
            </CardContent>
          </Card>
        </Link>
        <Link href={`/projects/${projectId}/outputs/gnn`}>
          <Card className="h-full transition-colors hover:bg-muted/50">
            <CardContent className="flex items-center gap-4 pt-6">
              <Network className="h-10 w-10 text-orange-500" />
              <div>
                <h3 className="font-medium">GNN Structure</h3>
                <p className="text-sm text-muted-foreground">Graph neural network data</p>
              </div>
            </CardContent>
          </Card>
        </Link>
      </div>

      {/* Files List */}
      {files.length === 0 ? (
        <Card>
          <CardContent className="flex flex-col items-center justify-center py-12 text-center">
            <FileCode className="mb-4 h-12 w-12 text-muted-foreground/30" />
            <h3 className="font-medium">No outputs yet</h3>
            <p className="mt-1 text-sm text-muted-foreground">
              Run the pipeline to generate AI-ready outputs
            </p>
            <Link href={`/projects/${projectId}`} className="mt-4">
              <Button>Go to Project</Button>
            </Link>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-6">
          {Object.entries(groupedFiles).map(([type, typeFiles]) => {
            const config = FILE_TYPE_CONFIG[type] || FILE_TYPE_CONFIG.other;
            const Icon = config.icon;

            return (
              <Card key={type}>
                <CardHeader>
                  <div className="flex items-center gap-3">
                    <Icon className={`h-5 w-5 ${config.color}`} />
                    <CardTitle className="text-base">{config.label}</CardTitle>
                    <Badge variant="secondary">{typeFiles.length} files</Badge>
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2">
                    {typeFiles.map((file) => (
                      <FileRow key={file.id} file={file} />
                    ))}
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}

      {/* Output Formats Info */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Output Format Reference</CardTitle>
          <CardDescription>
            The pipeline generates 4 AI-ready formats for different use cases
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4 md:grid-cols-2">
            <FormatInfo
              icon={Network}
              title="Knowledge Graph"
              description="RDF triples, property graphs for semantic reasoning and query"
              formats={["HTML (visualization)", "JSON (graph structure)"]}
            />
            <FormatInfo
              icon={Box}
              title="Text Embeddings"
              description="Dense vector representations for similarity search and RAG"
              formats={["NPY (NumPy array)", "Parquet (with metadata)"]}
            />
            <FormatInfo
              icon={Table}
              title="Tabular Dataset"
              description="Structured data for ML training and analysis"
              formats={["CSV", "Parquet"]}
            />
            <FormatInfo
              icon={Network}
              title="GNN Structure"
              description="Graph neural network ready format with node features and edges"
              formats={["JSON (PyTorch Geometric compatible)"]}
            />
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

function FileRow({ file }: { file: OutputFile }) {
  return (
    <div className="flex items-center justify-between rounded-md border p-3">
      <div className="flex items-center gap-3 min-w-0">
        <FileCode className="h-5 w-5 flex-shrink-0 text-muted-foreground" />
        <div className="min-w-0">
          <p className="truncate font-medium">{file.filename}</p>
          <p className="text-xs text-muted-foreground">
            {formatSize(file.size_kb)} • {file.mime_type}
          </p>
        </div>
      </div>
      <a href={file.download_url} download>
        <Button variant="ghost" size="sm">
          <Download className="h-4 w-4" />
        </Button>
      </a>
    </div>
  );
}

function FormatInfo({
  icon: Icon,
  title,
  description,
  formats,
}: {
  icon: React.ComponentType<any>;
  title: string;
  description: string;
  formats: string[];
}) {
  return (
    <div className="rounded-lg border p-4">
      <div className="flex items-center gap-2">
        <Icon className="h-4 w-4 text-primary" />
        <h4 className="font-medium">{title}</h4>
      </div>
      <p className="mt-1 text-sm text-muted-foreground">{description}</p>
      <div className="mt-2 flex flex-wrap gap-1">
        {formats.map((fmt) => (
          <Badge key={fmt} variant="outline" className="text-xs">
            {fmt}
          </Badge>
        ))}
      </div>
    </div>
  );
}

function formatSize(kb: number): string {
  if (kb < 1024) return `${kb.toFixed(1)} KB`;
  return `${(kb / 1024).toFixed(1)} MB`;
}
